version: '3.3'

services:
        api:
                build: .
                command: uvicorn main:app --host 0.0.0.0
                
                ports:
                        -  "8080:8080"
